class City {
  const City({
    required this.code,
    required this.countryCode,
    required this.nameEn,
    required this.nameRu,
    required this.nameLocal,
    required this.lat,
    required this.lon,
    required this.utcOffsetMinutes,
  });

  final String code;
  final String countryCode;
  final String nameEn;
  final String nameRu;
  final String nameLocal;
  final double lat;
  final double lon;
  final int utcOffsetMinutes;
}

const List<City> centralAsianCities = [
  City(
    code: 'TAS',
    countryCode: 'UZ',
    nameEn: 'Tashkent',
    nameRu: 'Ташкент',
    nameLocal: 'Toshkent',
    lat: 41.2995,
    lon: 69.2401,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'SKD',
    countryCode: 'UZ',
    nameEn: 'Samarkand',
    nameRu: 'Самарканд',
    nameLocal: 'Samarqand',
    lat: 39.6542,
    lon: 66.9597,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'BHK',
    countryCode: 'UZ',
    nameEn: 'Bukhara',
    nameRu: 'Бухара',
    nameLocal: 'Buxoro',
    lat: 39.7681,
    lon: 64.4556,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'AZN',
    countryCode: 'UZ',
    nameEn: 'Andijan',
    nameRu: 'Андижан',
    nameLocal: 'Andijon',
    lat: 40.7821,
    lon: 72.3442,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'NMA',
    countryCode: 'UZ',
    nameEn: 'Namangan',
    nameRu: 'Наманган',
    nameLocal: 'Namangan',
    lat: 40.9983,
    lon: 71.6726,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'FEG',
    countryCode: 'UZ',
    nameEn: 'Fergana',
    nameRu: 'Фергана',
    nameLocal: 'Fargʻona',
    lat: 40.3842,
    lon: 71.7843,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KSQ',
    countryCode: 'UZ',
    nameEn: 'Qarshi',
    nameRu: 'Карши',
    nameLocal: 'Qarshi',
    lat: 38.8606,
    lon: 65.7891,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'NCU',
    countryCode: 'UZ',
    nameEn: 'Nukus',
    nameRu: 'Нукус',
    nameLocal: 'Nukus',
    lat: 42.4619,
    lon: 59.6166,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'UGC',
    countryCode: 'UZ',
    nameEn: 'Urgench',
    nameRu: 'Ургенч',
    nameLocal: 'Urganch',
    lat: 41.5500,
    lon: 60.6333,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KHV',
    countryCode: 'UZ',
    nameEn: 'Khiva',
    nameRu: 'Хива',
    nameLocal: 'Xiva',
    lat: 41.3783,
    lon: 60.3639,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'TMJ',
    countryCode: 'UZ',
    nameEn: 'Termez',
    nameRu: 'Термез',
    nameLocal: 'Termiz',
    lat: 37.2242,
    lon: 67.2783,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'JZZ',
    countryCode: 'UZ',
    nameEn: 'Jizzakh',
    nameRu: 'Джизак',
    nameLocal: 'Jizzax',
    lat: 40.1158,
    lon: 67.8422,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'NVI',
    countryCode: 'UZ',
    nameEn: 'Navoi',
    nameRu: 'Навои',
    nameLocal: 'Navoiy',
    lat: 40.0844,
    lon: 65.3792,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'GUL',
    countryCode: 'UZ',
    nameEn: 'Gulistan',
    nameRu: 'Гулистан',
    nameLocal: 'Guliston',
    lat: 40.4897,
    lon: 68.7842,
    utcOffsetMinutes: 300,
  ),

  City(
    code: 'AST',
    countryCode: 'KZ',
    nameEn: 'Astana',
    nameRu: 'Астана',
    nameLocal: 'Астана',
    lat: 51.1694,
    lon: 71.4491,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'ALA',
    countryCode: 'KZ',
    nameEn: 'Almaty',
    nameRu: 'Алматы',
    nameLocal: 'Алматы',
    lat: 43.2389,
    lon: 76.8897,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'SHY',
    countryCode: 'KZ',
    nameEn: 'Shymkent',
    nameRu: 'Шымкент',
    nameLocal: 'Шымкент',
    lat: 42.3417,
    lon: 69.5901,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KGD',
    countryCode: 'KZ',
    nameEn: 'Karaganda',
    nameRu: 'Караганда',
    nameLocal: 'Қарағанды',
    lat: 49.8064,
    lon: 73.0855,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'AKT',
    countryCode: 'KZ',
    nameEn: 'Aktobe',
    nameRu: 'Актобе',
    nameLocal: 'Ақтөбе',
    lat: 50.2839,
    lon: 57.1669,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'TRZ',
    countryCode: 'KZ',
    nameEn: 'Taraz',
    nameRu: 'Тараз',
    nameLocal: 'Тараз',
    lat: 42.9000,
    lon: 71.3667,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'PAV',
    countryCode: 'KZ',
    nameEn: 'Pavlodar',
    nameRu: 'Павлодар',
    nameLocal: 'Павлодар',
    lat: 52.2873,
    lon: 76.9674,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'UKK',
    countryCode: 'KZ',
    nameEn: 'Oskemen',
    nameRu: 'Усть-Каменогорск',
    nameLocal: 'Өскемен',
    lat: 49.9483,
    lon: 82.6275,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'SEM',
    countryCode: 'KZ',
    nameEn: 'Semey',
    nameRu: 'Семей',
    nameLocal: 'Семей',
    lat: 50.4111,
    lon: 80.2275,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'ATY',
    countryCode: 'KZ',
    nameEn: 'Atyrau',
    nameRu: 'Атырау',
    nameLocal: 'Атырау',
    lat: 47.0945,
    lon: 51.9238,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KST',
    countryCode: 'KZ',
    nameEn: 'Kostanay',
    nameRu: 'Костанай',
    nameLocal: 'Қостанай',
    lat: 53.2198,
    lon: 63.6354,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KZO',
    countryCode: 'KZ',
    nameEn: 'Kyzylorda',
    nameRu: 'Кызылорда',
    nameLocal: 'Қызылорда',
    lat: 44.8488,
    lon: 65.4823,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'URA',
    countryCode: 'KZ',
    nameEn: 'Oral',
    nameRu: 'Уральск',
    nameLocal: 'Орал',
    lat: 51.2333,
    lon: 51.3667,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'PPK',
    countryCode: 'KZ',
    nameEn: 'Petropavl',
    nameRu: 'Петропавловск',
    nameLocal: 'Петропавл',
    lat: 54.8753,
    lon: 69.1628,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'SCO',
    countryCode: 'KZ',
    nameEn: 'Aktau',
    nameRu: 'Актау',
    nameLocal: 'Ақтау',
    lat: 43.6532,
    lon: 51.1975,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'TEM',
    countryCode: 'KZ',
    nameEn: 'Temirtau',
    nameRu: 'Темиртау',
    nameLocal: 'Теміртау',
    lat: 50.0549,
    lon: 72.9646,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'TUR',
    countryCode: 'KZ',
    nameEn: 'Turkistan',
    nameRu: 'Туркестан',
    nameLocal: 'Түркістан',
    lat: 43.2973,
    lon: 68.2518,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KOK',
    countryCode: 'KZ',
    nameEn: 'Kokshetau',
    nameRu: 'Кокшетау',
    nameLocal: 'Көкшетау',
    lat: 53.2833,
    lon: 69.3833,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'TDK',
    countryCode: 'KZ',
    nameEn: 'Taldykorgan',
    nameRu: 'Талдыкорган',
    nameLocal: 'Талдықорған',
    lat: 45.0156,
    lon: 78.3739,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'EKB',
    countryCode: 'KZ',
    nameEn: 'Ekibastuz',
    nameRu: 'Экибастуз',
    nameLocal: 'Екібастұз',
    lat: 51.7298,
    lon: 75.3266,
    utcOffsetMinutes: 300,
  ),

  City(
    code: 'BIS',
    countryCode: 'KG',
    nameEn: 'Bishkek',
    nameRu: 'Бишкек',
    nameLocal: 'Бишкек',
    lat: 42.8746,
    lon: 74.5698,
    utcOffsetMinutes: 360,
  ),
  City(
    code: 'OSS',
    countryCode: 'KG',
    nameEn: 'Osh',
    nameRu: 'Ош',
    nameLocal: 'Ош',
    lat: 40.5139,
    lon: 72.8161,
    utcOffsetMinutes: 360,
  ),
  City(
    code: 'JAL',
    countryCode: 'KG',
    nameEn: 'Jalal-Abad',
    nameRu: 'Джалал-Абад',
    nameLocal: 'Жалал-Абад',
    lat: 40.9333,
    lon: 73.0000,
    utcOffsetMinutes: 360,
  ),
  City(
    code: 'KRL',
    countryCode: 'KG',
    nameEn: 'Karakol',
    nameRu: 'Каракол',
    nameLocal: 'Каракол',
    lat: 42.4907,
    lon: 78.3936,
    utcOffsetMinutes: 360,
  ),
  City(
    code: 'TOK',
    countryCode: 'KG',
    nameEn: 'Tokmok',
    nameRu: 'Токмок',
    nameLocal: 'Токмок',
    lat: 42.8419,
    lon: 75.3015,
    utcOffsetMinutes: 360,
  ),
  City(
    code: 'NAR',
    countryCode: 'KG',
    nameEn: 'Naryn',
    nameRu: 'Нарын',
    nameLocal: 'Нарын',
    lat: 41.4287,
    lon: 75.9911,
    utcOffsetMinutes: 360,
  ),
  City(
    code: 'TAL',
    countryCode: 'KG',
    nameEn: 'Talas',
    nameRu: 'Талас',
    nameLocal: 'Талас',
    lat: 42.5228,
    lon: 72.2427,
    utcOffsetMinutes: 360,
  ),
  City(
    code: 'BAT',
    countryCode: 'KG',
    nameEn: 'Batken',
    nameRu: 'Баткен',
    nameLocal: 'Баткен',
    lat: 40.0626,
    lon: 70.8194,
    utcOffsetMinutes: 360,
  ),

  City(
    code: 'DYU',
    countryCode: 'TJ',
    nameEn: 'Dushanbe',
    nameRu: 'Душанбе',
    nameLocal: 'Душанбе',
    lat: 38.5598,
    lon: 68.7870,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'LBD',
    countryCode: 'TJ',
    nameEn: 'Khujand',
    nameRu: 'Худжанд',
    nameLocal: 'Хуҷанд',
    lat: 40.2833,
    lon: 69.6333,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KQT',
    countryCode: 'TJ',
    nameEn: 'Bokhtar',
    nameRu: 'Бохтар',
    nameLocal: 'Бохтар',
    lat: 37.8364,
    lon: 68.7803,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'TJU',
    countryCode: 'TJ',
    nameEn: 'Kulob',
    nameRu: 'Куляб',
    nameLocal: 'Кӯлоб',
    lat: 37.9146,
    lon: 69.7845,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'IST',
    countryCode: 'TJ',
    nameEn: 'Istaravshan',
    nameRu: 'Истаравшан',
    nameLocal: 'Истаравшан',
    lat: 39.9142,
    lon: 69.0033,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KHO',
    countryCode: 'TJ',
    nameEn: 'Khorugh',
    nameRu: 'Хорог',
    nameLocal: 'Хоруғ',
    lat: 37.4917,
    lon: 71.5558,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'TSD',
    countryCode: 'TJ',
    nameEn: 'Tursunzoda',
    nameRu: 'Турсунзаде',
    nameLocal: 'Турсунзода',
    lat: 38.5127,
    lon: 68.2316,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'PNJ',
    countryCode: 'TJ',
    nameEn: 'Panjakent',
    nameRu: 'Пенджикент',
    nameLocal: 'Панҷакент',
    lat: 39.4952,
    lon: 67.6093,
    utcOffsetMinutes: 300,
  ),

  City(
    code: 'ASB',
    countryCode: 'TM',
    nameEn: 'Ashgabat',
    nameRu: 'Ашхабад',
    nameLocal: 'Aşgabat',
    lat: 37.9601,
    lon: 58.3261,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'CRZ',
    countryCode: 'TM',
    nameEn: 'Turkmenabat',
    nameRu: 'Туркменабад',
    nameLocal: 'Türkmenabat',
    lat: 39.0733,
    lon: 63.5786,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'TAZ',
    countryCode: 'TM',
    nameEn: 'Dasoguz',
    nameRu: 'Дашогуз',
    nameLocal: 'Daşoguz',
    lat: 41.8363,
    lon: 59.9666,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'MYP',
    countryCode: 'TM',
    nameEn: 'Mary',
    nameRu: 'Мары',
    nameLocal: 'Mary',
    lat: 37.5938,
    lon: 61.8303,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'BKN',
    countryCode: 'TM',
    nameEn: 'Balkanabat',
    nameRu: 'Балканабад',
    nameLocal: 'Balkanabat',
    lat: 39.5108,
    lon: 54.3671,
    utcOffsetMinutes: 300,
  ),
  City(
    code: 'KRW',
    countryCode: 'TM',
    nameEn: 'Turkmenbasy',
    nameRu: 'Туркменбаши',
    nameLocal: 'Türkmenbaşy',
    lat: 40.0230,
    lon: 52.9697,
    utcOffsetMinutes: 300,
  ),
];
